services:
  - type: web
    name: clash-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python clash.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.15
